-- flow control with exception handler that does not re-rasie error

DECLARE
    V_NUMBER NUMBER;
BEGIN
    --SATRT EMEBEDED BLOCK
    BEGIN
        V_NUMBER := 'ABC';
    EXCEPTION
        WHEN OTHERS THEN 
            DBMS_OUTPUT.PUT_LINE('WHEN OTHERS');
    END;
    -- END EMBADED BLOCK
    DBMS_OUTPUT.PUT_LINE('NEXT LINE');
END;
/
    
    
-- flow control with exception handler that does re-rasie error

DECLARE
    V_NUMBER NUMBER;
BEGIN
    --SATRT EMEBEDED BLOCK
    BEGIN
        V_NUMBER := 'ABC';
    EXCEPTION
        WHEN OTHERS THEN 
            DBMS_OUTPUT.PUT_LINE('WHEN OTHERS');
            RAISE;
    END;
    -- END EMBADED BLOCK
    DBMS_OUTPUT.PUT_LINE('NEXT LINE');
END;
/
    
    
-- flow control with exception handler that does  re-rasie error
-- WHICH IS THEN GET TRAPPED
DECLARE
    V_NUMBER NUMBER;
BEGIN
    --SATRT EMEBEDED BLOCK
    BEGIN
        V_NUMBER := 'ABC';
    EXCEPTION
        WHEN OTHERS THEN 
            DBMS_OUTPUT.PUT_LINE('WHEN OTHERS');
            RAISE;
    END;
    -- END EMBADED BLOCK
    DBMS_OUTPUT.PUT_LINE('NEXT LINE');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OTHER WHEN OTHERS');
END;
/
    
    
-- RAISE AN ERROR DIRECTLY 
BEGIN
    RAISE NO_DATA_FOUND;
END;
/

-- raise an error direclty,handle it and 
-- raise somthing 
BEGIN
    RAISE NO_DATA_FOUND;
EXCEPTION
    WHEN NO_dATA_FOUND THEN
        RAISE DUP_VAL_ON_INDEX;
END;
/


-- EXCEPTION HANDLER CAN AFFECT THE TRANSACTIONS
SELECT * FROM 
    ANIMAL;

-- UNIQUE CONSTANT ERROR FOR WHOLE TRANSATION    
BEGIN
    INSERT INTO ANIMAL VALUES (3,'ELEPHANT');
    INSERT INTO ANIMAL VALUES (2,'LION');
END;
/

-- RAISE ERROR ONLY ERROR FOR DUPLICATE STATEMETN
BEGIN
    INSERT INTO ANIMAL VALUES (3,'ELEPHANT');
    INSERT INTO ANIMAL VALUES (2,'LION');
    INSERT INTO ANIMAL VALUES (4,'HIPPO');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL;
END;
/

-- HIPPO RECORD WIL NOT CREATE DUE TO JUM OF EXCEPTION HANDLER
SELECT * FROM
    ANIMAL;
