-- PRE-DEFINE EXCEPTIONS 
-- 20+ AVAIBLES

-- USE OF GENERIC WHEN OTHERS HANDLES
DECLARE
    V_NUMBER NUMBER := 11;
BEGIN
    V_NUMBER := V_NUMBER / 0;
EXCEPTION 
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OTEHRS '|| SQLCODE);
        DBMS_OUTPUT.PUT_LINE('OTEHRS '|| SQLERRM);
END;
/


-- USE OF PRE-DEFINE HANDLER ADN WHE OTHERS
DECLARE
    V_NUMBER NUMBER := 11;
BEGIN
    V_NUMBER := V_NUMBER / 0;
EXCEPTION 
    -- HANDLER FOR ZERO DIVIDE ERRRO
    WHEN ZERO_DIVIDE THEN
        DBMS_OUTPUT.PUT_LINE('ZERO '|| SQLCODE);
        DBMS_OUTPUT.PUT_LINE('ZERO '|| SQLERRM);
    --- HANDLER FOR ALL OTHER ERRORS
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OTEHRS '|| SQLCODE);
        DBMS_OUTPUT.PUT_LINE('OTEHRS '|| SQLERRM);
END;
/


-- NO DATA FOUND AND TOO MANY ROWS WHEN QUERYING
-- RECORDS FORM DB
DECLARE
    V_ANIMAL_NAME ANIMAL.animal_name%TYPE;
BEGIN
    SELECT ANIMAL_NAME INTO V_ANIMAL_NAME FROM 
    ANIMAL
    WHERE ANIMAL_ID =99;
EXCEPTION
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('TOO MANY ROWS FOUND');
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
        -- NO_DATA_FOUND IS EQUAL TO ORA-01403 BUT IT SHOW AS SQLCODE 100
        DBMS_OUTPUT.PUT_LINE(SQLCODE);
END;
/

SELECT
    * FROM aNIMAL;
    
BEGIN
    INSERT INTO ANIMAL VALUES(2,'lION');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        UPDATE ANIMAL 
        SET ANIMAL_NAME = 'LION'
        WHERE ANIMAL_ID = 2;
END;