    -- NESTED CURSOR
-- AKA CURSOR EXPRESSIONS
-- CURSSOR WITH CURSORS
-- BEHAVE AS REF CURSOR

-- query of animal and tehr stripes
SELECT *
    FROM ANIMAL A,
        ANIMAL_STRIPES AST
    WHERE A.ANIMAL_ID = AST.ANIMAL_ID
    ORDER BY A.ANIMAL_ID;
    
    