/*
|	Program: Verification of Profier tables 
|	Author: Raahool Kumeriya
|	Change history:
|		27-MAY-2022 - Program Created
*/

SET SERVEROUTPUT ON;
SET PAGES 1000 LINES 192;

COL TABLE_NAME FORMAT A20;
COL CLUSTER_NAME FORMAT A20;
COL IOT_NAME FORMAT A20;
COL DEFAULT_COLLATION FORMAT A20;
COL INMEMORY_SERVICE_NAME FORMAT A20;
COL CLUSTER_OWNER FORMAT A20;

SELECT 	TABLE_NAME
,	TABLESPACE_NAME
,	STATUS
,	INSTANCES
FROM user_tables
WHERE table_name LIKE '%PROF%';

