SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE proc1 IS
BEGIN
	DBMS_OUTPUT.PUT_LINE('running proc1');
	RAISE NO_DATA_FOUND;
END;
/

CREATE OR REPLACE PROCEDURE proc2 IS
	l_str VARCHAR2(30) := 'calling proc1';
BEGIN
	DBMS_OUTPUT.PUT_LINE(l_str);
	proc1;
END;
/

CREATE OR REPLACE PROCEDURE proc3 IS
BEGIN
	DBMS_OUTPUT.PUT_LINE('calling proc2');
	proc2;
EXCEPTION
	WHEN OTHERS
	THEN
		DBMS_OUTPUT.PUT_LINE('Error stack at top level:');
		DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.format_error_backtrace);
END;
/


BEGIN
	DBMS_OUTPUT.put_line('Proc3 -> Proc2 -> Proc1 backtrace');
	proc3;
END;
/

