---
- name: "testing custom module | version_change"
  hosts: "{{ remote_host }}" 
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
  - name: Test that my change_version module works
    version_change: 
      version_name: "Before"
      version_no:  1.1.1 
      unchanged_value: "This will pass through"
    register: result

  - debug: var=result 
