---
- name: "testing custom module | hello_world"
  hosts: "{{ remote_host }}" 
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
  - name: Test that my hello_world module works
    hello_world:
    register: result

  - debug: var=result
