---
- name: "testing custom module | pmon_status" 
  hosts: "{{ remote_host }}" 
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: pmon process check for database instance
      pmon_status: 
        instance: "{{ database_instance }}" 
      register: result
    - debug: var=result 
